# Generated by Django 3.1.1 on 2020-09-03 06:51

from django.db import migrations, models
import json
import os

from pathlib import Path
from ..models import Movie


def load_movies_from_files():
    DIR = Path(__file__).parent.parent.parent.parent
    file_path = str(DIR) + "/dummy-data.json"
    print('File Path', file_path)
    with open(file_path, 'r') as fd:
        movies = json.loads(fd.read())
        for movie in movies:
            print(movie)
            m = Movie.create(
                name=movie['name'], release_date=movie['release_date'], description=movie['description'])
            m.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        # load_movies_from_files()
    ]
